# Initialization

## Libraries

In [1]:
%load_ext autoreload
%autoreload 2

from skopt import gp_minimize
from skopt.space import Real, Categorical
from skopt.learning import GaussianProcessRegressor
from skopt.learning.gaussian_process.kernels import Matern, RBF

import warnings
import numpy as np
import pandas as pd
from pathlib import Path

## Directories

In [2]:
data_dir = Path("data")
Path.mkdir(data_dir, exist_ok=True)

plot_dir = Path("plots")
Path.mkdir(plot_dir, exist_ok=True)

log_dir = Path("logs")
Path.mkdir(log_dir, exist_ok=True)

## Data reading

In [3]:
data_file = "Dataset_SL.xlsx"

### Define experimental data

In [6]:
# 1. Define the experimental data
experiment_data = pd.read_excel(data_dir / data_file, sheet_name="Datasheet")

In [7]:
# make the other columns as floats
experiment_data = experiment_data.astype(
    {
        "salt_concentration": float,
        "water_to_cement_ratio": float,
        "antisettling_concentration": float,
        "E_d": float,
        "KPI": float,
    }
)

# get optimization round for later use in saving
opt_round = experiment_data["opt_round"].iloc[-1]

In [8]:
experiment_data

,opt_round,salt,salt_concentration,water_to_cement_ratio,antisettling_concentration,kernel,acquisition,obj_func,E_d,KPI
0,0,MgSO4,0.5,1.0,0.0,NaN,NaN,NaN,27.764640,9.597843
1,0,CaCl2,0.5,1.0,0.0,NaN,NaN,NaN,87.715788,2.519732
2,0,SrBr2,0.5,1.0,0.0,NaN,NaN,NaN,95.547176,53.682419
3,0,MgCl2,0.5,1.0,0.0,NaN,NaN,NaN,82.071086,2.933749
4,0,CuSO4,0.5,1.0,0.0,NaN,NaN,NaN,5.954210,100.212303
5,0,Al2(SO4)3,0.5,1.0,0.0,NaN,NaN,NaN,14.944089,15.671044
6,0,K2CO3,0.5,1.0,0.0,NaN,NaN,NaN,23.614710,38.117562
7,0,KAl(SO4)2,0.5,1.0,0.0,NaN,NaN,NaN,26.974859,7.504554
8,0,LiCl,0.5,1.0,0.0,NaN,NaN,NaN,158.387724,53.476998
9,0,Mg(NO3)2,0.5,1.0,0.0,NaN,NaN,NaN,55.930893,9.326240
10,0,Zn(NO3)2,0.5,1.0,0.0,NaN,NaN,NaN,69.053644,14.331143
11,0,MgSO4,0.7,1.5,0.2,NaN,NaN,NaN,22.524587,13.125281
12,0,CaCl2,0.8,1.0,3.0,NaN,NaN,NaN,129.351966,3.543489
13,0,SrBr2,0.4,0.7,2.0,NaN,NaN,NaN,55.495032,71.609620
14,0,MgCl2,0.6,0.9,1.2,NaN,NaN,NaN,80.774071,4.378630
15,0,CuSO4,0.9,1.0,0.6,NaN,NaN,NaN,7.385310,126.784384
16,0,Al2(SO4)3,0.8,1.1,0.4,NaN,NaN,NaN,17.117516,16.633126
17,0,K2CO3,0.5,0.8,1.5,NaN,NaN,NaN,14.791589,66.701693
18,0,KAl(SO4)2,0.9,1.4,0.8,NaN,NaN,NaN,21.465078,12.188863
19,0,LiCl,0.1,0.7,2.5,NaN,NaN,NaN,43.940096,49.642305
20,0,Mg(NO3)2,0.2,1.3,1.7,NaN,NaN,NaN,38.822344,12.258519
21,0,Zn(NO3)2,0.3,1.2,2.2,NaN,NaN,NaN,42.970217,21.468990

# Search space

### Category encoding

In [9]:
cat_order = [
    "Al2(SO4)3",
    "CaCl2",
    "CuSO4",
    "K2CO3",
    "KAl(SO4)2",
    "LiCl",
    "Mg(NO3)2",
    "MgCl2",
    "MgSO4",
    "SrBr2",
    "Zn(NO3)2",
]

cat_mapping = {name: i for i, name in enumerate(cat_order)}

df_enc = experiment_data.copy()
df_enc["category_encoded"] = experiment_data["salt"].map(cat_mapping)
df_enc

,opt_round,salt,salt_concentration,water_to_cement_ratio,antisettling_concentration,kernel,acquisition,obj_func,E_d,KPI,category_encoded
0,0,MgSO4,0.5,1.0,0.0,NaN,NaN,NaN,27.764640,9.597843,8
1,0,CaCl2,0.5,1.0,0.0,NaN,NaN,NaN,87.715788,2.519732,1
2,0,SrBr2,0.5,1.0,0.0,NaN,NaN,NaN,95.547176,53.682419,9
3,0,MgCl2,0.5,1.0,0.0,NaN,NaN,NaN,82.071086,2.933749,7
4,0,CuSO4,0.5,1.0,0.0,NaN,NaN,NaN,5.954210,100.212303,2
5,0,Al2(SO4)3,0.5,1.0,0.0,NaN,NaN,NaN,14.944089,15.671044,0
6,0,K2CO3,0.5,1.0,0.0,NaN,NaN,NaN,23.614710,38.117562,3
7,0,KAl(SO4)2,0.5,1.0,0.0,NaN,NaN,NaN,26.974859,7.504554,4
8,0,LiCl,0.5,1.0,0.0,NaN,NaN,NaN,158.387724,53.476998,5
9,0,Mg(NO3)2,0.5,1.0,0.0,NaN,NaN,NaN,55.930893,9.326240,6
10,0,Zn(NO3)2,0.5,1.0,0.0,NaN,NaN,NaN,69.053644,14.331143,10
11,0,MgSO4,0.7,1.5,0.2,NaN,NaN,NaN,22.524587,13.125281,8
12,0,CaCl2,0.8,1.0,3.0,NaN,NaN,NaN,129.351966,3.543489,1
13,0,SrBr2,0.4,0.7,2.0,NaN,NaN,NaN,55.495032,71.609620,9
14,0,MgCl2,0.6,0.9,1.2,NaN,NaN,NaN,80.774071,4.378630,7
15,0,CuSO4,0.9,1.0,0.6,NaN,NaN,NaN,7.385310,126.784384,2
16,0,Al2(SO4)3,0.8,1.1,0.4,NaN,NaN,NaN,17.117516,16.633126,0
17,0,K2CO3,0.5,0.8,1.5,NaN,NaN,NaN,14.791589,66.701693,3
18,0,KAl(SO4)2,0.9,1.4,0.8,NaN,NaN,NaN,21.465078,12.188863,4
19,0,LiCl,0.1,0.7,2.5,NaN,NaN,NaN,43.940096,49.642305,5
20,0,Mg(NO3)2,0.2,1.3,1.7,NaN,NaN,NaN,38.822344,12.258519,6
21,0,Zn(NO3)2,0.3,1.2,2.2,NaN,NaN,NaN,42.970217,21.468990,10

In [10]:
search_space = [
    Categorical(cat_order, name="salt"),  # salt names
    Real(0.1, 0.9, name="salt_concentration"),
    Real(0.7, 1.5, name="water_to_cement_ratio"),
    Real(0.0, 3.0, name="antisettling_concentration"),
]

# Optimization

In [11]:
salt_dummies = pd.get_dummies(df_enc["salt"], prefix="salt").reindex(
    columns=[f"salt_{cat}" for cat in cat_order], fill_value=0
)

In [12]:
X = pd.concat(
    [
        salt_dummies,
        df_enc[
            [
                "salt_concentration",
                "water_to_cement_ratio",
                "antisettling_concentration",
            ]
        ],
    ],
    axis=1,
).to_numpy()
y_energy = df_enc["E_d"].values
y_kpi = df_enc["KPI"].values

In [13]:
salt_dummies

,salt_Al2(SO4)3,salt_CaCl2,salt_CuSO4,salt_K2CO3,salt_KAl(SO4)2,salt_LiCl,salt_Mg(NO3)2,salt_MgCl2,salt_MgSO4,salt_SrBr2,salt_Zn(NO3)2
0,False,False,False,False,False,False,False,False,True,False,False
1,False,True,False,False,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False,False,False,True,False
3,False,False,False,False,False,False,False,True,False,False,False
4,False,False,True,False,False,False,False,False,False,False,False
5,True,False,False,False,False,False,False,False,False,False,False
6,False,False,False,True,False,False,False,False,False,False,False
7,False,False,False,False,True,False,False,False,False,False,False
8,False,False,False,False,False,True,False,False,False,False,False
9,False,False,False,False,False,False,True,False,False,False,False
10,False,False,False,False,False,False,False,False,False,False,True
11,False,False,False,False,False,False,False,False,True,False,False
12,False,True,False,False,False,False,False,False,False,False,False
13,False,False,False,False,False,False,False,False,False,True,False
14,False,False,False,False,False,False,False,True,False,False,False
15,False,False,True,False,False,False,False,False,False,False,False
16,True,False,False,False,False,False,False,False,False,False,False
17,False,False,False,True,False,False,False,False,False,False,False
18,False,False,False,False,True,False,False,False,False,False,False
19,False,False,False,False,False,True,False,False,False,False,False
20,False,False,False,False,False,False,True,False,False,False,False
21,False,False,False,False,False,False,False,False,False,False,True

## Gaussian Process

In [14]:
def fit_gp_models(X, y, kernel):
    """Fits Gaussian Process models to the given experimental data."""  # noqa

    gp = GaussianProcessRegressor(
        kernel=kernel,
        normalize_y=True,
        n_restarts_optimizer=10,
        alpha=1e-3,
    )

    gp.fit(X, y)

    return gp

### Matern kernel

In [15]:
gp_energy_matern = fit_gp_models(
    X,
    -y_energy,
    Matern(length_scale=5e-3, length_scale_bounds=(1e-8, 10.0), nu=2.5),  # noqa
)

In [16]:
gp_kpi_matern = fit_gp_models(
    X,
    y_kpi,
    Matern(length_scale=5e-3, length_scale_bounds=(1e-8, 10.0), nu=2.5),  # noqa
)

### RBF kernel

In [17]:
gp_energy_rbf = fit_gp_models(
    X,
    -y_energy,
    RBF(
        length_scale=5e-3,
        length_scale_bounds=(1e-8, 10.0),
    ),
)

In [18]:
gp_kpi_rbf = fit_gp_models(
    X,
    y_kpi,
    RBF(
        length_scale=5e-3,
        length_scale_bounds=(1e-8, 10.0),
    ),
)

# Bayesian Optimization

In [19]:
def encode_input(x):
    # x[0] is salt name (e.g., "MgSO4")
    salt_vector = np.zeros(len(cat_mapping))
    salt_index = cat_mapping[x[0]]
    salt_vector[salt_index] = 1

    # concatenate with continuous features
    return np.concatenate([salt_vector, np.array(x[1:])])

In [29]:
def suggest_new_samples(
    gp_model: GaussianProcessRegressor,
    obj_func: str,
    print_points: bool = False,
    verbose: bool = False,
    mute_warnings: bool = True,
):
    """Suggests new samples based on the trained GP model using different acquisition functions."""  # noqa

    acq_functions = ["EI", "PI", "LCB_low", "LCB_med", "LCB_high"]
    kappa_values = {
        "LCB_low": 1.0,
        "LCB_med": 2.5,
        "LCB_high": 5.0,
    }
    new_samples = []

    with warnings.catch_warnings():
        if mute_warnings:
            print("Warnings are muted!")
            warnings.simplefilter("ignore")

        for i, acquisition in enumerate(acq_functions):
            res = gp_minimize(
                lambda x: gp_model.predict([encode_input(x)])[
                    0
                ],  # Optimize our surrogate model # noqa
                dimensions=search_space,  # pass our search space
                base_estimator=gp_model,
                acq_func=(
                    "LCB"
                    if acquisition in ["LCB_low", "LCB_med", "LCB_high"]
                    else acquisition
                ),  # define the acquisition function
                kappa=kappa_values.get(
                    acquisition
                ),  # define the custom k value if acquisition if "LCB" # noqa
                xi=0.05,
                n_calls=40,
                verbose=verbose,
                n_jobs=6,
            )

            # Convert numerical salt encoding back to categorical
            suggested = res.x
            if print_points:
                print(suggested)

            suggested.append(str(gp_model.kernel).split("(")[0])
            suggested.append(str(acquisition))
            suggested.append(str(obj_func))

            # save suggested samples in a list
            new_samples.append(suggested)

    # create a new dataframe with suggested samples
    columns = [
        "salt",
        "salt_concentration",
        "water_to_cement_ratio",
        "antisettling_concentration",
        "kernel",
        "acquisition",
        "obj_func",
    ]

    df = pd.DataFrame(new_samples, columns=columns)

    # round float values to 3rd decimal place
    df[df.select_dtypes(include="float").columns] = df.select_dtypes(
        include="float"
    ).round(3)

    return df

### Generate 10 new samples for Energy Density optimization

In [30]:
# Matérn kernel
new_samples_energy_matern = suggest_new_samples(
    gp_energy_matern, obj_func="E_d", verbose=True, mute_warnings=True
)

Warnings are muted!
Iteration No: 1 started. Evaluating function at random point.
Iteration No: 1 ended. Evaluation done at random point.
Time taken: 0.0010
Function value obtained: -71.6662
Current minimum: -71.6662
Iteration No: 2 started. Evaluating function at random point.
Iteration No: 2 ended. Evaluation done at random point.
Time taken: 0.0000
Function value obtained: -18.1907
Current minimum: -71.6662
Iteration No: 3 started. Evaluating function at random point.
Iteration No: 3 ended. Evaluation done at random point.
Time taken: 0.0000
Function value obtained: -46.2839
Current minimum: -71.6662
Iteration No: 4 started. Evaluating function at random point.
Iteration No: 4 ended. Evaluation done at random point.
Time taken: 0.0010
Function value obtained: -50.1032
Current minimum: -71.6662
Iteration No: 5 started. Evaluating function at random point.
Iteration No: 5 ended. Evaluation done at random point.
Time taken: 0.0000
Function value obtained: -27.1229
Current minimum: -71.6662
Iteration No: 6 started. Evaluating function at random point.
Iteration No: 6 ended. Evaluation done at random point.
Time taken: 0.0000
Function value obtained: -84.6905
Current minimum: -84.6905
Iteration No: 7 started. Evaluating function at random point.
Iteration No: 7 ended. Evaluation done at random point.
Time taken: 0.0000
Function value obtained: -43.2382
Current minimum: -84.6905
Iteration No: 8 started. Evaluating function at random point.
Iteration No: 8 ended. Evaluation done at random point.
Time taken: 0.0000
Function value obtained: -64.7746
Current minimum: -84.6905
Iteration No: 9 started. Evaluating function at random point.
Iteration No: 9 ended. Evaluation done at random point.
Time taken: 0.0000
Function value obtained: -61.5862
Current minimum: -84.6905
Iteration No: 10 started. Evaluating function at random point.
Iteration No: 10 ended. Evaluation done at random point.
Time taken: 0.1474
Function value obtained: -21.9361
Current minimum: -84.6905
Iteration No: 11 started. Searching for the next optimal point.
Iteration No: 11 ended. Search finished for the next optimal point.
Time taken: 0.0644
Function value obtained: -83.0675
Current minimum: -84.6905
Iteration No: 12 started. Searching for the next optimal point.
Iteration No: 12 ended. Search finished for the next optimal point.
Time taken: 0.0680
Function value obtained: -91.7284
Current minimum: -91.7284
Iteration No: 13 started. Searching for the next optimal point.
Iteration No: 13 ended. Search finished for the next optimal point.
Time taken: 0.0901
Function value obtained: -87.4306
Current minimum: -91.7284
Iteration No: 14 started. Searching for the next optimal point.
Iteration No: 14 ended. Search finished for the next optimal point.
Time taken: 0.1123
Function value obtained: -93.9275
Current minimum: -93.9275
Iteration No: 15 started. Searching for the next optimal point.
Iteration No: 15 ended. Search finished for the next optimal point.
Time taken: 0.0794
Function value obtained: -94.4310
Current minimum: -94.4310
Iteration No: 16 started. Searching for the next optimal point.
Iteration No: 16 ended. Search finished for the next optimal point.
Time taken: 0.0692
Function value obtained: -94.8573
Current minimum: -94.8573
Iteration No: 17 started. Searching for the next optimal point.
Iteration No: 17 ended. Search finished for the next optimal point.
Time taken: 0.0955
Function value obtained: -95.1460
Current minimum: -95.1460
Iteration No: 18 started. Searching for the next optimal point.
Iteration No: 18 ended. Search finished for the next optimal point.
Time taken: 0.1071
Function value obtained: -95.2623
Current minimum: -95.2623
Iteration No: 19 started. Searching for the next optimal point.
Iteration No: 19 ended. Search finished for the next optimal point.
Time taken: 0.1078
Function value obtained: -95.2891
Current minimum: -95.2891
Iteration No: 20 started. Searching for the next optimal point.
Iteration No: 20 ended. Search finished for the next optimal point.
Time taken: 0.2185
Function value obtained: -95.2934
Current minimum: -95.2934
Iteration No: 21 started. Searching for the next optimal point.
Iteration No: 21 ended. Search finished for the next optimal point.
Time taken: 0.0996
Function value obtained: -95.2916
Current minimum: -95.2934
Iteration No: 22 started. Searching for the next optimal point.
Iteration No: 22 ended. Search finished for the next optimal point.
Time taken: 0.0796
Function value obtained: -95.2857
Current minimum: -95.2934
Iteration No: 23 started. Searching for the next optimal point.
Iteration No: 23 ended. Search finished for the next optimal point.
Time taken: 0.1065
Function value obtained: -95.2756
Current minimum: -95.2934
Iteration No: 24 started. Searching for the next optimal point.
Iteration No: 24 ended. Search finished for the next optimal point.
Time taken: 0.0675
Function value obtained: -95.2604
Current minimum: -95.2934
Iteration No: 25 started. Searching for the next optimal point.
Iteration No: 25 ended. Search finished for the next optimal point.
Time taken: 0.0633
Function value obtained: -95.2387
Current minimum: -95.2934
Iteration No: 26 started. Searching for the next optimal point.
Iteration No: 26 ended. Search finished for the next optimal point.
Time taken: 0.0864
Function value obtained: -81.8541
Current minimum: -95.2934
Iteration No: 27 started. Searching for the next optimal point.
Iteration No: 27 ended. Search finished for the next optimal point.
Time taken: 0.0979
Function value obtained: -82.1123
Current minimum: -95.2934
Iteration No: 28 started. Searching for the next optimal point.
Iteration No: 28 ended. Search finished for the next optimal point.
Time taken: 0.0792
Function value obtained: -82.2332
Current minimum: -95.2934
Iteration No: 29 started. Searching for the next optimal point.
Iteration No: 29 ended. Search finished for the next optimal point.
Time taken: 0.1091
Function value obtained: -82.2611
Current minimum: -95.2934
Iteration No: 30 started. Searching for the next optimal point.
Iteration No: 30 ended. Search finished for the next optimal point.
Time taken: 0.2453
Function value obtained: -82.2562
Current minimum: -95.2934
Iteration No: 31 started. Searching for the next optimal point.
Iteration No: 31 ended. Search finished for the next optimal point.
Time taken: 0.0796
Function value obtained: -82.2472
Current minimum: -95.2934
Iteration No: 32 started. Searching for the next optimal point.
Iteration No: 32 ended. Search finished for the next optimal point.
Time taken: 0.0885
Function value obtained: -82.2397
Current minimum: -95.2934
Iteration No: 33 started. Searching for the next optimal point.
Iteration No: 33 ended. Search finished for the next optimal point.
Time taken: 0.1845
Function value obtained: -82.2348
Current minimum: -95.2934
Iteration No: 34 started. Searching for the next optimal point.
Iteration No: 34 ended. Search finished for the next optimal point.
Time taken: 0.2469
Function value obtained: -82.2321
Current minimum: -95.2934
Iteration No: 35 started. Searching for the next optimal point.
Iteration No: 35 ended. Search finished for the next optimal point.
Time taken: 0.1367
Function value obtained: -82.2310
Current minimum: -95.2934
Iteration No: 36 started. Searching for the next optimal point.
Iteration No: 36 ended. Search finished for the next optimal point.
Time taken: 0.2126
Function value obtained: -82.2311
Current minimum: -95.2934
Iteration No: 37 started. Searching for the next optimal point.
Iteration No: 37 ended. Search finished for the next optimal point.
Time taken: 0.2390
Function value obtained: -82.2318
Current minimum: -95.2934
Iteration No: 38 started. Searching for the next optimal point.
Iteration No: 38 ended. Search finished for the next optimal point.
Time taken: 0.1156
Function value obtained: -95.3990
Current minimum: -95.3990
Iteration No: 39 started. Searching for the next optimal point.
Iteration No: 39 ended. Search finished for the next optimal point.
Time taken: 0.1462
Function value obtained: -82.2305
Current minimum: -95.3990
Iteration No: 40 started. Searching for the next optimal point.
Iteration No: 40 ended. Search finished for the next optimal point.
Time taken: 0.2456
Function value obtained: -82.2325
Current minimum: -95.3990
Iteration No: 1 started. Evaluating function at random point.
Iteration No: 1 ended. Evaluation done at random point.
Time taken: 0.0000
Function value obtained: -36.9585
Current minimum: -36.9585
Iteration No: 2 started. Evaluating function at random point.
Iteration No: 2 ended. Evaluation done at random point.
Time taken: 0.0000
Function value obtained: -6.1578
Current minimum: -36.9585
Iteration No: 3 started. Evaluating function at random point.
Iteration No: 3 ended. Evaluation done at random point.
Time taken: 0.0000
Function value obtained: -34.3099
Current minimum: -36.9585
Iteration No: 4 started. Evaluating function at random point.
Iteration No: 4 ended. Evaluation done at random point.
Time taken: 0.0000
Function value obtained: -44.2241
Current minimum: -44.2241
Iteration No: 5 started. Evaluating function at random point.
Iteration No: 5 ended. Evaluation done at random point.
Time taken: 0.0000
Function value obtained: -57.9793
Current minimum: -57.9793
Iteration No: 6 started. Evaluating function at random point.
Iteration No: 6 ended. Evaluation done at random point.
Time taken: 0.0000
Function value obtained: -66.9237
Current minimum: -66.9237
Iteration No: 7 started. Evaluating function at random point.
Iteration No: 7 ended. Evaluation done at random point.
Time taken: 0.0000
Function value obtained: -74.2048
Current minimum: -74.2048
Iteration No: 8 started. Evaluating function at random point.
Iteration No: 8 ended. Evaluation done at random point.
Time taken: 0.0000
Function value obtained: -18.5492
Current minimum: -74.2048
Iteration No: 9 started. Evaluating function at random point.
Iteration No: 9 ended. Evaluation done at random point.
Time taken: 0.0000
Function value obtained: -9.1308
Current minimum: -74.2048
Iteration No: 10 started. Evaluating function at random point.
Iteration No: 10 ended. Evaluation done at random point.
Time taken: 0.0481
Function value obtained: -56.4123
Current minimum: -74.2048
Iteration No: 11 started. Searching for the next optimal point.
Iteration No: 11 ended. Search finished for the next optimal point.
Time taken: 0.0534
Function value obtained: -56.6253
Current minimum: -74.2048
Iteration No: 12 started. Searching for the next optimal point.
Iteration No: 12 ended. Search finished for the next optimal point.
Time taken: 0.0634
Function value obtained: -73.2364
Current minimum: -74.2048
Iteration No: 13 started. Searching for the next optimal point.
Iteration No: 13 ended. Search finished for the next optimal point.
Time taken: 0.0939
Function value obtained: -77.6488
Current minimum: -77.6488
Iteration No: 14 started. Searching for the next optimal point.
Iteration No: 14 ended. Search finished for the next optimal point.
Time taken: 0.0716
Function value obtained: -79.6560
Current minimum: -79.6560
Iteration No: 15 started. Searching for the next optimal point.
Iteration No: 15 ended. Search finished for the next optimal point.
Time taken: 0.1032
Function value obtained: -80.6798
Current minimum: -80.6798
Iteration No: 16 started. Searching for the next optimal point.
Iteration No: 16 ended. Search finished for the next optimal point.
Time taken: 0.1154
Function value obtained: -81.1876
Current minimum: -81.1876
Iteration No: 17 started. Searching for the next optimal point.
Iteration No: 17 ended. Search finished for the next optimal point.
Time taken: 0.0707
Function value obtained: -81.4958
Current minimum: -81.4958
Iteration No: 18 started. Searching for the next optimal point.
Iteration No: 18 ended. Search finished for the next optimal point.
Time taken: 0.0636
Function value obtained: -81.6971
Current minimum: -81.6971
Iteration No: 19 started. Searching for the next optimal point.
Iteration No: 19 ended. Search finished for the next optimal point.
Time taken: 0.0804
Function value obtained: -81.8155
Current minimum: -81.8155
Iteration No: 20 started. Searching for the next optimal point.
Iteration No: 20 ended. Search finished for the next optimal point.
Time taken: 0.1711
Function value obtained: -81.8706
Current minimum: -81.8706
Iteration No: 21 started. Searching for the next optimal point.
Iteration No: 21 ended. Search finished for the next optimal point.
Time taken: 0.0815
Function value obtained: -81.8696
Current minimum: -81.8706
Iteration No: 22 started. Searching for the next optimal point.
Iteration No: 22 ended. Search finished for the next optimal point.
Time taken: 0.0635
Function value obtained: -81.8610
Current minimum: -81.8706
Iteration No: 23 started. Searching for the next optimal point.
Iteration No: 23 ended. Search finished for the next optimal point.
Time taken: 0.0694
Function value obtained: -81.8604
Current minimum: -81.8706
Iteration No: 24 started. Searching for the next optimal point.
Iteration No: 24 ended. Search finished for the next optimal point.
Time taken: 0.0659
Function value obtained: -81.8603
Current minimum: -81.8706
Iteration No: 25 started. Searching for the next optimal point.
Iteration No: 25 ended. Search finished for the next optimal point.
Time taken: 0.0999
Function value obtained: -81.8603
Current minimum: -81.8706
Iteration No: 26 started. Searching for the next optimal point.
Iteration No: 26 ended. Search finished for the next optimal point.
Time taken: 0.1164
Function value obtained: -81.8601
Current minimum: -81.8706
Iteration No: 27 started. Searching for the next optimal point.
Iteration No: 27 ended. Search finished for the next optimal point.
Time taken: 0.0829
Function value obtained: -81.8599
Current minimum: -81.8706
Iteration No: 28 started. Searching for the next optimal point.
Iteration No: 28 ended. Search finished for the next optimal point.
Time taken: 0.1152
Function value obtained: -81.8596
Current minimum: -81.8706
Iteration No: 29 started. Searching for the next optimal point.
Iteration No: 29 ended. Search finished for the next optimal point.
Time taken: 0.2012
Function value obtained: -81.8592
Current minimum: -81.8706
Iteration No: 30 started. Searching for the next optimal point.
Iteration No: 30 ended. Search finished for the next optimal point.
Time taken: 0.0831
Function value obtained: -81.8588
Current minimum: -81.8706
Iteration No: 31 started. Searching for the next optimal point.
Iteration No: 31 ended. Search finished for the next optimal point.
Time taken: 0.1486
Function value obtained: -81.8584
Current minimum: -81.8706
Iteration No: 32 started. Searching for the next optimal point.
Iteration No: 32 ended. Search finished for the next optimal point.
Time taken: 0.1003
Function value obtained: -81.8580
Current minimum: -81.8706
Iteration No: 33 started. Searching for the next optimal point.
Iteration No: 33 ended. Search finished for the next optimal point.
Time taken: 0.1851
Function value obtained: -81.8576
Current minimum: -81.8706
Iteration No: 34 started. Searching for the next optimal point.
Iteration No: 34 ended. Search finished for the next optimal point.
Time taken: 0.1676
Function value obtained: -81.8572
Current minimum: -81.8706
Iteration No: 35 started. Searching for the next optimal point.
Iteration No: 35 ended. Search finished for the next optimal point.
Time taken: 0.2348
Function value obtained: -81.8568
Current minimum: -81.8706
Iteration No: 36 started. Searching for the next optimal point.
Iteration No: 36 ended. Search finished for the next optimal point.
Time taken: 0.1612
Function value obtained: -81.8565
Current minimum: -81.8706
Iteration No: 37 started. Searching for the next optimal point.
Iteration No: 37 ended. Search finished for the next optimal point.
Time taken: 0.2387
Function value obtained: -81.8562
Current minimum: -81.8706
Iteration No: 38 started. Searching for the next optimal point.
Iteration No: 38 ended. Search finished for the next optimal point.
Time taken: 0.1954
Function value obtained: -81.8559
Current minimum: -81.8706
Iteration No: 39 started. Searching for the next optimal point.
Iteration No: 39 ended. Search finished for the next optimal point.
Time taken: 0.2869
Function value obtained: -81.8556
Current minimum: -81.8706
Iteration No: 40 started. Searching for the next optimal point.
Iteration No: 40 ended. Search finished for the next optimal point.
Time taken: 0.1301
Function value obtained: -81.8554
Current minimum: -81.8706
Iteration No: 1 started. Evaluating function at random point.
Iteration No: 1 ended. Evaluation done at random point.
Time taken: 0.0020
Function value obtained: -45.6389
Current minimum: -45.6389
Iteration No: 2 started. Evaluating function at random point.
Iteration No: 2 ended. Evaluation done at random point.
Time taken: 0.0000
Function value obtained: -42.0157
Current minimum: -45.6389
Iteration No: 3 started. Evaluating function at random point.
Iteration No: 3 ended. Evaluation done at random point.
Time taken: 0.0000
Function value obtained: -55.6117
Current minimum: -55.6117
Iteration No: 4 started. Evaluating function at random point.
Iteration No: 4 ended. Evaluation done at random point.
Time taken: 0.0000
Function value obtained: -62.7377
Current minimum: -62.7377
Iteration No: 5 started. Evaluating function at random point.
Iteration No: 5 ended. Evaluation done at random point.
Time taken: 0.0020
Function value obtained: -18.7650
Current minimum: -62.7377
Iteration No: 6 started. Evaluating function at random point.
Iteration No: 6 ended. Evaluation done at random point.
Time taken: 0.0000
Function value obtained: -31.2278
Current minimum: -62.7377
Iteration No: 7 started. Evaluating function at random point.
Iteration No: 7 ended. Evaluation done at random point.
Time taken: 0.0000
Function value obtained: -19.3338
Current minimum: -62.7377
Iteration No: 8 started. Evaluating function at random point.
Iteration No: 8 ended. Evaluation done at random point.
Time taken: 0.0020
Function value obtained: -57.7885
Current minimum: -62.7377
Iteration No: 9 started. Evaluating function at random point.
Iteration No: 9 ended. Evaluation done at random point.
Time taken: 0.0000
Function value obtained: -44.7087
Current minimum: -62.7377
Iteration No: 10 started. Evaluating function at random point.
Iteration No: 10 ended. Evaluation done at random point.
Time taken: 0.0889
Function value obtained: -32.0855
Current minimum: -62.7377
Iteration No: 11 started. Searching for the next optimal point.
Iteration No: 11 ended. Search finished for the next optimal point.
Time taken: 0.0658
Function value obtained: -49.7206
Current minimum: -62.7377
Iteration No: 12 started. Searching for the next optimal point.
Iteration No: 12 ended. Search finished for the next optimal point.
Time taken: 0.0479
Function value obtained: -62.5752
Current minimum: -62.7377
Iteration No: 13 started. Searching for the next optimal point.
Iteration No: 13 ended. Search finished for the next optimal point.
Time taken: 0.0702
Function value obtained: -91.8254
Current minimum: -91.8254
Iteration No: 14 started. Searching for the next optimal point.
Iteration No: 14 ended. Search finished for the next optimal point.
Time taken: 0.0716
Function value obtained: -111.3314
Current minimum: -111.3314
Iteration No: 15 started. Searching for the next optimal point.
Iteration No: 15 ended. Search finished for the next optimal point.
Time taken: 0.0588
Function value obtained: -127.8403
Current minimum: -127.8403
Iteration No: 16 started. Searching for the next optimal point.
Iteration No: 16 ended. Search finished for the next optimal point.
Time taken: 0.0523
Function value obtained: -123.1172
Current minimum: -127.8403
Iteration No: 17 started. Searching for the next optimal point.
Iteration No: 17 ended. Search finished for the next optimal point.

In [31]:
new_samples_energy_matern

,salt,salt_concentration,water_to_cement_ratio,antisettling_concentration,kernel,acquisition,obj_func
0,SrBr2,0.517,0.910,0.00,Matern,EI,E_d
1,MgCl2,0.315,0.997,0.44,Matern,PI,E_d
2,LiCl,0.432,1.500,0.00,Matern,LCB_low,E_d
3,LiCl,0.900,0.700,0.00,Matern,LCB_med,E_d
4,CaCl2,0.470,0.941,0.00,Matern,LCB_high,E_d

In [32]:
# RBF kernel
new_samples_energy_rbf = suggest_new_samples(
    gp_energy_rbf, obj_func="E_d", verbose=True, mute_warnings=True
)

Warnings are muted!
Iteration No: 1 started. Evaluating function at random point.
Iteration No: 1 ended. Evaluation done at random point.
Time taken: 0.0000
Function value obtained: -27.9048
Current minimum: -27.9048
Iteration No: 2 started. Evaluating function at random point.
Iteration No: 2 ended. Evaluation done at random point.
Time taken: 0.0000
Function value obtained: -17.3134
Current minimum: -27.9048
Iteration No: 3 started. Evaluating function at random point.
Iteration No: 3 ended. Evaluation done at random point.
Time taken: 0.0000
Function value obtained: -28.2485
Current minimum: -28.2485
Iteration No: 4 started. Evaluating function at random point.
Iteration No: 4 ended. Evaluation done at random point.
Time taken: 0.0000
Function value obtained: -10.2883
Current minimum: -28.2485
Iteration No: 5 started. Evaluating function at random point.
Iteration No: 5 ended. Evaluation done at random point.
Time taken: 0.0000
Function value obtained: -77.7035
Current minimum: -77.7035
Iteration No: 6 started. Evaluating function at random point.
Iteration No: 6 ended. Evaluation done at random point.
Time taken: 0.0000
Function value obtained: -72.0354
Current minimum: -77.7035
Iteration No: 7 started. Evaluating function at random point.
Iteration No: 7 ended. Evaluation done at random point.
Time taken: 0.0000
Function value obtained: -27.5323
Current minimum: -77.7035
Iteration No: 8 started. Evaluating function at random point.
Iteration No: 8 ended. Evaluation done at random point.
Time taken: 0.0000
Function value obtained: -80.7787
Current minimum: -80.7787
Iteration No: 9 started. Evaluating function at random point.
Iteration No: 9 ended. Evaluation done at random point.
Time taken: 0.0000
Function value obtained: -79.4270
Current minimum: -80.7787
Iteration No: 10 started. Evaluating function at random point.
Iteration No: 10 ended. Evaluation done at random point.
Time taken: 0.0492
Function value obtained: -70.0708
Current minimum: -80.7787
Iteration No: 11 started. Searching for the next optimal point.
Iteration No: 11 ended. Search finished for the next optimal point.
Time taken: 0.0479
Function value obtained: -80.3130
Current minimum: -80.7787
Iteration No: 12 started. Searching for the next optimal point.
Iteration No: 12 ended. Search finished for the next optimal point.
Time taken: 0.0517
Function value obtained: -79.0023
Current minimum: -80.7787
Iteration No: 13 started. Searching for the next optimal point.
Iteration No: 13 ended. Search finished for the next optimal point.
Time taken: 0.0669
Function value obtained: -78.6774
Current minimum: -80.7787
Iteration No: 14 started. Searching for the next optimal point.
Iteration No: 14 ended. Search finished for the next optimal point.
Time taken: 0.0890
Function value obtained: -79.1750
Current minimum: -80.7787
Iteration No: 15 started. Searching for the next optimal point.
Iteration No: 15 ended. Search finished for the next optimal point.
Time taken: 0.0471
Function value obtained: -78.9230
Current minimum: -80.7787
Iteration No: 16 started. Searching for the next optimal point.
Iteration No: 16 ended. Search finished for the next optimal point.
Time taken: 0.0518
Function value obtained: -79.0606
Current minimum: -80.7787
Iteration No: 17 started. Searching for the next optimal point.
Iteration No: 17 ended. Search finished for the next optimal point.
Time taken: 0.1636
Function value obtained: -79.1386
Current minimum: -80.7787
Iteration No: 18 started. Searching for the next optimal point.
Iteration No: 18 ended. Search finished for the next optimal point.
Time taken: 0.0800
Function value obtained: -79.2153
Current minimum: -80.7787
Iteration No: 19 started. Searching for the next optimal point.
Iteration No: 19 ended. Search finished for the next optimal point.
Time taken: 0.0634
Function value obtained: -79.3035
Current minimum: -80.7787
Iteration No: 20 started. Searching for the next optimal point.
Iteration No: 20 ended. Search finished for the next optimal point.
Time taken: 0.0671
Function value obtained: -79.4152
Current minimum: -80.7787
Iteration No: 21 started. Searching for the next optimal point.
Iteration No: 21 ended. Search finished for the next optimal point.
Time taken: 0.0519
Function value obtained: -79.5707
Current minimum: -80.7787
Iteration No: 22 started. Searching for the next optimal point.
Iteration No: 22 ended. Search finished for the next optimal point.
Time taken: 0.0513
Function value obtained: -79.8072
Current minimum: -80.7787
Iteration No: 23 started. Searching for the next optimal point.
Iteration No: 23 ended. Search finished for the next optimal point.
Time taken: 0.0847
Function value obtained: -80.1808
Current minimum: -80.7787
Iteration No: 24 started. Searching for the next optimal point.
Iteration No: 24 ended. Search finished for the next optimal point.
Time taken: 0.0742
Function value obtained: -80.6969
Current minimum: -80.7787
Iteration No: 25 started. Searching for the next optimal point.
Iteration No: 25 ended. Search finished for the next optimal point.
Time taken: 0.0907
Function value obtained: -81.0757
Current minimum: -81.0757
Iteration No: 26 started. Searching for the next optimal point.
Iteration No: 26 ended. Search finished for the next optimal point.
Time taken: 0.1009
Function value obtained: -81.0677
Current minimum: -81.0757
Iteration No: 27 started. Searching for the next optimal point.
Iteration No: 27 ended. Search finished for the next optimal point.
Time taken: 0.0829
Function value obtained: -81.1024
Current minimum: -81.1024
Iteration No: 28 started. Searching for the next optimal point.
Iteration No: 28 ended. Search finished for the next optimal point.
Time taken: 0.1812
Function value obtained: -81.1210
Current minimum: -81.1210
Iteration No: 29 started. Searching for the next optimal point.
Iteration No: 29 ended. Search finished for the next optimal point.
Time taken: 0.0856
Function value obtained: -81.1374
Current minimum: -81.1374
Iteration No: 30 started. Searching for the next optimal point.
Iteration No: 30 ended. Search finished for the next optimal point.
Time taken: 0.1400
Function value obtained: -81.1521
Current minimum: -81.1521
Iteration No: 31 started. Searching for the next optimal point.
Iteration No: 31 ended. Search finished for the next optimal point.
Time taken: 0.0756
Function value obtained: -81.1653
Current minimum: -81.1653
Iteration No: 32 started. Searching for the next optimal point.
Iteration No: 32 ended. Search finished for the next optimal point.
Time taken: 0.0683
Function value obtained: -81.1774
Current minimum: -81.1774
Iteration No: 33 started. Searching for the next optimal point.
Iteration No: 33 ended. Search finished for the next optimal point.
Time taken: 0.2487
Function value obtained: -81.1884
Current minimum: -81.1884
Iteration No: 34 started. Searching for the next optimal point.
Iteration No: 34 ended. Search finished for the next optimal point.
Time taken: 0.1263
Function value obtained: -81.1984
Current minimum: -81.1984
Iteration No: 35 started. Searching for the next optimal point.
Iteration No: 35 ended. Search finished for the next optimal point.
Time taken: 0.1076
Function value obtained: -81.2075
Current minimum: -81.2075
Iteration No: 36 started. Searching for the next optimal point.
Iteration No: 36 ended. Search finished for the next optimal point.
Time taken: 0.0986
Function value obtained: -81.2159
Current minimum: -81.2159
Iteration No: 37 started. Searching for the next optimal point.
Iteration No: 37 ended. Search finished for the next optimal point.
Time taken: 0.1651
Function value obtained: -81.2234
Current minimum: -81.2234
Iteration No: 38 started. Searching for the next optimal point.
Iteration No: 38 ended. Search finished for the next optimal point.
Time taken: 0.2837
Function value obtained: -81.2303
Current minimum: -81.2303
Iteration No: 39 started. Searching for the next optimal point.
Iteration No: 39 ended. Search finished for the next optimal point.
Time taken: 0.1827
Function value obtained: -81.2366
Current minimum: -81.2366
Iteration No: 40 started. Searching for the next optimal point.
Iteration No: 40 ended. Search finished for the next optimal point.
Time taken: 0.1352
Function value obtained: -81.2423
Current minimum: -81.2423
Iteration No: 1 started. Evaluating function at random point.
Iteration No: 1 ended. Evaluation done at random point.
Time taken: 0.0000
Function value obtained: -16.8169
Current minimum: -16.8169
Iteration No: 2 started. Evaluating function at random point.
Iteration No: 2 ended. Evaluation done at random point.
Time taken: 0.0100
Function value obtained: -18.7792
Current minimum: -18.7792
Iteration No: 3 started. Evaluating function at random point.
Iteration No: 3 ended. Evaluation done at random point.
Time taken: 0.0011
Function value obtained: -42.5648
Current minimum: -42.5648
Iteration No: 4 started. Evaluating function at random point.
Iteration No: 4 ended. Evaluation done at random point.
Time taken: 0.0000
Function value obtained: -83.5418
Current minimum: -83.5418
Iteration No: 5 started. Evaluating function at random point.
Iteration No: 5 ended. Evaluation done at random point.
Time taken: 0.0000
Function value obtained: -64.6463
Current minimum: -83.5418
Iteration No: 6 started. Evaluating function at random point.
Iteration No: 6 ended. Evaluation done at random point.
Time taken: 0.0000
Function value obtained: -67.3902
Current minimum: -83.5418
Iteration No: 7 started. Evaluating function at random point.
Iteration No: 7 ended. Evaluation done at random point.
Time taken: 0.0000
Function value obtained: -7.4613
Current minimum: -83.5418
Iteration No: 8 started. Evaluating function at random point.
Iteration No: 8 ended. Evaluation done at random point.
Time taken: 0.0000
Function value obtained: -60.2615
Current minimum: -83.5418
Iteration No: 9 started. Evaluating function at random point.
Iteration No: 9 ended. Evaluation done at random point.
Time taken: 0.0000
Function value obtained: -45.8874
Current minimum: -83.5418
Iteration No: 10 started. Evaluating function at random point.
Iteration No: 10 ended. Evaluation done at random point.
Time taken: 0.0479
Function value obtained: -58.0944
Current minimum: -83.5418
Iteration No: 11 started. Searching for the next optimal point.
Iteration No: 11 ended. Search finished for the next optimal point.
Time taken: 0.0717
Function value obtained: -65.1146
Current minimum: -83.5418
Iteration No: 12 started. Searching for the next optimal point.
Iteration No: 12 ended. Search finished for the next optimal point.
Time taken: 0.0989
Function value obtained: -77.9881
Current minimum: -83.5418
Iteration No: 13 started. Searching for the next optimal point.
Iteration No: 13 ended. Search finished for the next optimal point.
Time taken: 0.0930
Function value obtained: -90.8396
Current minimum: -90.8396
Iteration No: 14 started. Searching for the next optimal point.
Iteration No: 14 ended. Search finished for the next optimal point.
Time taken: 0.0689
Function value obtained: -93.9778
Current minimum: -93.9778
Iteration No: 15 started. Searching for the next optimal point.
Iteration No: 15 ended. Search finished for the next optimal point.
Time taken: 0.0950
Function value obtained: -94.1402
Current minimum: -94.1402
Iteration No: 16 started. Searching for the next optimal point.
Iteration No: 16 ended. Search finished for the next optimal point.
Time taken: 0.1069
Function value obtained: -94.1273
Current minimum: -94.1402
Iteration No: 17 started. Searching for the next optimal point.
Iteration No: 17 ended. Search finished for the next optimal point.
Time taken: 0.0839
Function value obtained: -94.1277
Current minimum: -94.1402
Iteration No: 18 started. Searching for the next optimal point.
Iteration No: 18 ended. Search finished for the next optimal point.
Time taken: 0.1988
Function value obtained: -94.1280
Current minimum: -94.1402
Iteration No: 19 started. Searching for the next optimal point.
Iteration No: 19 ended. Search finished for the next optimal point.
Time taken: 0.0863
Function value obtained: -94.1282
Current minimum: -94.1402
Iteration No: 20 started. Searching for the next optimal point.
Iteration No: 20 ended. Search finished for the next optimal point.
Time taken: 0.0986
Function value obtained: -94.1284
Current minimum: -94.1402
Iteration No: 21 started. Searching for the next optimal point.
Iteration No: 21 ended. Search finished for the next optimal point.
Time taken: 0.1861
Function value obtained: -94.1284
Current minimum: -94.1402
Iteration No: 22 started. Searching for the next optimal point.
Iteration No: 22 ended. Search finished for the next optimal point.
Time taken: 0.1506
Function value obtained: -94.1285
Current minimum: -94.1402
Iteration No: 23 started. Searching for the next optimal point.
Iteration No: 23 ended. Search finished for the next optimal point.
Time taken: 0.0794
Function value obtained: -94.1285
Current minimum: -94.1402
Iteration No: 24 started. Searching for the next optimal point.
Iteration No: 24 ended. Search finished for the next optimal point.
Time taken: 0.0950
Function value obtained: -94.1285
Current minimum: -94.1402
Iteration No: 25 started. Searching for the next optimal point.
Iteration No: 25 ended. Search finished for the next optimal point.
Time taken: 0.0701
Function value obtained: -94.1286
Current minimum: -94.1402
Iteration No: 26 started. Searching for the next optimal point.
Iteration No: 26 ended. Search finished for the next optimal point.
Time taken: 0.0668
Function value obtained: -94.1097
Current minimum: -94.1402
Iteration No: 27 started. Searching for the next optimal point.
Iteration No: 27 ended. Search finished for the next optimal point.
Time taken: 0.0647
Function value obtained: -94.1719
Current minimum: -94.1719
Iteration No: 28 started. Searching for the next optimal point.
Iteration No: 28 ended. Search finished for the next optimal point.
Time taken: 0.0840
Function value obtained: -94.1802
Current minimum: -94.1802
Iteration No: 29 started. Searching for the next optimal point.
Iteration No: 29 ended. Search finished for the next optimal point.
Time taken: 0.1483
Function value obtained: -93.8589
Current minimum: -94.1802
Iteration No: 30 started. Searching for the next optimal point.
Iteration No: 30 ended. Search finished for the next optimal point.
Time taken: 0.0814
Function value obtained: -94.4872
Current minimum: -94.4872
Iteration No: 31 started. Searching for the next optimal point.
Iteration No: 31 ended. Search finished for the next optimal point.
Time taken: 0.0719
Function value obtained: -94.9634
Current minimum: -94.9634
Iteration No: 32 started. Searching for the next optimal point.
Iteration No: 32 ended. Search finished for the next optimal point.
Time taken: 0.1154
Function value obtained: -95.3507
Current minimum: -95.3507
Iteration No: 33 started. Searching for the next optimal point.
Iteration No: 33 ended. Search finished for the next optimal point.
Time taken: 0.1684
Function value obtained: -95.5944
Current minimum: -95.5944
Iteration No: 34 started. Searching for the next optimal point.
Iteration No: 34 ended. Search finished for the next optimal point.
Time taken: 0.1353
Function value obtained: -95.6518
Current minimum: -95.6518
Iteration No: 35 started. Searching for the next optimal point.
Iteration No: 35 ended. Search finished for the next optimal point.
Time taken: 0.1591
Function value obtained: -95.6469
Current minimum: -95.6518
Iteration No: 36 started. Searching for the next optimal point.
Iteration No: 36 ended. Search finished for the next optimal point.
Time taken: 0.1840
Function value obtained: -95.7319
Current minimum: -95.7319
Iteration No: 37 started. Searching for the next optimal point.
Iteration No: 37 ended. Search finished for the next optimal point.
Time taken: 0.1191
Function value obtained: -95.7825
Current minimum: -95.7825
Iteration No: 38 started. Searching for the next optimal point.
Iteration No: 38 ended. Search finished for the next optimal point.
Time taken: 0.2840
Function value obtained: -95.7848
Current minimum: -95.7848
Iteration No: 39 started. Searching for the next optimal point.
Iteration No: 39 ended. Search finished for the next optimal point.
Time taken: 0.0988
Function value obtained: -95.7821
Current minimum: -95.7848
Iteration No: 40 started. Searching for the next optimal point.
Iteration No: 40 ended. Search finished for the next optimal point.
Time taken: 0.1182
Function value obtained: -95.7826
Current minimum: -95.7848
Iteration No: 1 started. Evaluating function at random point.
Iteration No: 1 ended. Evaluation done at random point.
Time taken: 0.0000
Function value obtained: -30.2942
Current minimum: -30.2942
Iteration No: 2 started. Evaluating function at random point.
Iteration No: 2 ended. Evaluation done at random point.
Time taken: 0.0000
Function value obtained: -49.2424
Current minimum: -49.2424
Iteration No: 3 started. Evaluating function at random point.
Iteration No: 3 ended. Evaluation done at random point.
Time taken: 0.0000
Function value obtained: -66.6475
Current minimum: -66.6475
Iteration No: 4 started. Evaluating function at random point.
Iteration No: 4 ended. Evaluation done at random point.
Time taken: 0.0000
Function value obtained: -43.0423
Current minimum: -66.6475
Iteration No: 5 started. Evaluating function at random point.
Iteration No: 5 ended. Evaluation done at random point.
Time taken: 0.0000
Function value obtained: -48.8053
Current minimum: -66.6475
Iteration No: 6 started. Evaluating function at random point.
Iteration No: 6 ended. Evaluation done at random point.
Time taken: 0.0000
Function value obtained: -84.8065
Current minimum: -84.8065
Iteration No: 7 started. Evaluating function at random point.
Iteration No: 7 ended. Evaluation done at random point.
Time taken: 0.0000
Function value obtained: -37.9595
Current minimum: -84.8065
Iteration No: 8 started. Evaluating function at random point.
Iteration No: 8 ended. Evaluation done at random point.
Time taken: 0.0000
Function value obtained: -55.3382
Current minimum: -84.8065
Iteration No: 9 started. Evaluating function at random point.
Iteration No: 9 ended. Evaluation done at random point.
Time taken: 0.0000
Function value obtained: -27.6660
Current minimum: -84.8065
Iteration No: 10 started. Evaluating function at random point.
Iteration No: 10 ended. Evaluation done at random point.
Time taken: 0.0598
Function value obtained: -72.8179
Current minimum: -84.8065
Iteration No: 11 started. Searching for the next optimal point.
Iteration No: 11 ended. Search finished for the next optimal point.
Time taken: 0.0506
Function value obtained: -84.0782
Current minimum: -84.8065
Iteration No: 12 started. Searching for the next optimal point.
Iteration No: 12 ended. Search finished for the next optimal point.
Time taken: 0.0517
Function value obtained: -116.3087
Current minimum: -116.3087
Iteration No: 13 started. Searching for the next optimal point.
Iteration No: 13 ended. Search finished for the next optimal point.
Time taken: 0.0636
Function value obtained: -72.6886
Current minimum: -116.3087
Iteration No: 14 started. Searching for the next optimal point.
Iteration No: 14 ended. Search finished for the next optimal point.
Time taken: 0.0822
Function value obtained: -119.0955
Current minimum: -119.0955
Iteration No: 15 started. Searching for the next optimal point.
Iteration No: 15 ended. Search finished for the next optimal point.
Time taken: 0.0880
Function value obtained: -109.9505
Current minimum: -119.0955
Iteration No: 16 started. Searching for the next optimal point.
Iteration No: 16 ended. Search finished for the next optimal point.
Time taken: 0.0489
Function value obtained: -121.2208
Current minimum: -121.2208
Iteration No: 17 started. Searching for the next optimal point.

In [33]:
new_samples_energy_rbf

,salt,salt_concentration,water_to_cement_ratio,antisettling_concentration,kernel,acquisition,obj_func
0,MgCl2,0.279,1.044,0.0,RBF,EI,E_d
1,SrBr2,0.450,0.920,0.0,RBF,PI,E_d
2,CaCl2,0.846,0.980,3.0,RBF,LCB_low,E_d
3,SrBr2,0.900,1.088,3.0,RBF,LCB_med,E_d
4,CaCl2,0.739,0.854,0.0,RBF,LCB_high,E_d

### Generate 10 new samples for economic KPI optimization

In [34]:
# Matérn kernel
new_samples_kpi_matern = suggest_new_samples(
    gp_kpi_matern, obj_func="KPI", verbose=True, mute_warnings=True
)

Warnings are muted!
Iteration No: 1 started. Evaluating function at random point.
Iteration No: 1 ended. Evaluation done at random point.
Time taken: 0.0000
Function value obtained: 12.6381
Current minimum: 12.6381
Iteration No: 2 started. Evaluating function at random point.
Iteration No: 2 ended. Evaluation done at random point.
Time taken: 0.0000
Function value obtained: 58.5774
Current minimum: 12.6381
Iteration No: 3 started. Evaluating function at random point.
Iteration No: 3 ended. Evaluation done at random point.
Time taken: 0.0000
Function value obtained: 52.0904
Current minimum: 12.6381
Iteration No: 4 started. Evaluating function at random point.
Iteration No: 4 ended. Evaluation done at random point.
Time taken: 0.0000
Function value obtained: 20.2485
Current minimum: 12.6381
Iteration No: 5 started. Evaluating function at random point.
Iteration No: 5 ended. Evaluation done at random point.
Time taken: 0.0000
Function value obtained: 49.0816
Current minimum: 12.6381
Iteration No: 6 started. Evaluating function at random point.
Iteration No: 6 ended. Evaluation done at random point.
Time taken: 0.0000
Function value obtained: 13.2853
Current minimum: 12.6381
Iteration No: 7 started. Evaluating function at random point.
Iteration No: 7 ended. Evaluation done at random point.
Time taken: 0.0000
Function value obtained: 2.2970
Current minimum: 2.2970
Iteration No: 8 started. Evaluating function at random point.
Iteration No: 8 ended. Evaluation done at random point.
Time taken: 0.0000
Function value obtained: 15.1295
Current minimum: 2.2970
Iteration No: 9 started. Evaluating function at random point.
Iteration No: 9 ended. Evaluation done at random point.
Time taken: 0.0000
Function value obtained: 29.0067
Current minimum: 2.2970
Iteration No: 10 started. Evaluating function at random point.
Iteration No: 10 ended. Evaluation done at random point.
Time taken: 0.0502
Function value obtained: 55.1094
Current minimum: 2.2970
Iteration No: 11 started. Searching for the next optimal point.
Iteration No: 11 ended. Search finished for the next optimal point.
Time taken: 0.0754
Function value obtained: 12.6903
Current minimum: 2.2970
Iteration No: 12 started. Searching for the next optimal point.
Iteration No: 12 ended. Search finished for the next optimal point.
Time taken: 0.1338
Function value obtained: 3.0476
Current minimum: 2.2970
Iteration No: 13 started. Searching for the next optimal point.
Iteration No: 13 ended. Search finished for the next optimal point.
Time taken: 0.0739
Function value obtained: 2.2287
Current minimum: 2.2287
Iteration No: 14 started. Searching for the next optimal point.
Iteration No: 14 ended. Search finished for the next optimal point.
Time taken: 0.0830
Function value obtained: 2.3004
Current minimum: 2.2287
Iteration No: 15 started. Searching for the next optimal point.
Iteration No: 15 ended. Search finished for the next optimal point.
Time taken: 0.1017
Function value obtained: 2.2580
Current minimum: 2.2287
Iteration No: 16 started. Searching for the next optimal point.
Iteration No: 16 ended. Search finished for the next optimal point.
Time taken: 0.0709
Function value obtained: 2.2320
Current minimum: 2.2287
Iteration No: 17 started. Searching for the next optimal point.
Iteration No: 17 ended. Search finished for the next optimal point.
Time taken: 0.1819
Function value obtained: 2.1500
Current minimum: 2.1500
Iteration No: 18 started. Searching for the next optimal point.
Iteration No: 18 ended. Search finished for the next optimal point.
Time taken: 0.0729
Function value obtained: 1.7774
Current minimum: 1.7774
Iteration No: 19 started. Searching for the next optimal point.
Iteration No: 19 ended. Search finished for the next optimal point.
Time taken: 0.1238
Function value obtained: 0.8852
Current minimum: 0.8852
Iteration No: 20 started. Searching for the next optimal point.
Iteration No: 20 ended. Search finished for the next optimal point.
Time taken: 0.0646
Function value obtained: 0.8624
Current minimum: 0.8624
Iteration No: 21 started. Searching for the next optimal point.
Iteration No: 21 ended. Search finished for the next optimal point.
Time taken: 0.0891
Function value obtained: 0.8473
Current minimum: 0.8473
Iteration No: 22 started. Searching for the next optimal point.
Iteration No: 22 ended. Search finished for the next optimal point.
Time taken: 0.1680
Function value obtained: 0.8393
Current minimum: 0.8393
Iteration No: 23 started. Searching for the next optimal point.
Iteration No: 23 ended. Search finished for the next optimal point.
Time taken: 0.1022
Function value obtained: 0.8310
Current minimum: 0.8310
Iteration No: 24 started. Searching for the next optimal point.
Iteration No: 24 ended. Search finished for the next optimal point.
Time taken: 0.0869
Function value obtained: 0.8223
Current minimum: 0.8223
Iteration No: 25 started. Searching for the next optimal point.
Iteration No: 25 ended. Search finished for the next optimal point.
Time taken: 0.0865
Function value obtained: 0.8138
Current minimum: 0.8138
Iteration No: 26 started. Searching for the next optimal point.
Iteration No: 26 ended. Search finished for the next optimal point.
Time taken: 0.2011
Function value obtained: 0.8089
Current minimum: 0.8089
Iteration No: 27 started. Searching for the next optimal point.
Iteration No: 27 ended. Search finished for the next optimal point.
Time taken: 0.1375
Function value obtained: 0.8141
Current minimum: 0.8089
Iteration No: 28 started. Searching for the next optimal point.
Iteration No: 28 ended. Search finished for the next optimal point.
Time taken: 0.0800
Function value obtained: 0.8283
Current minimum: 0.8089
Iteration No: 29 started. Searching for the next optimal point.
Iteration No: 29 ended. Search finished for the next optimal point.
Time taken: 0.1154
Function value obtained: 0.8397
Current minimum: 0.8089
Iteration No: 30 started. Searching for the next optimal point.
Iteration No: 30 ended. Search finished for the next optimal point.
Time taken: 0.0823
Function value obtained: 0.8454
Current minimum: 0.8089
Iteration No: 31 started. Searching for the next optimal point.
Iteration No: 31 ended. Search finished for the next optimal point.
Time taken: 0.0675
Function value obtained: 0.8484
Current minimum: 0.8089
Iteration No: 32 started. Searching for the next optimal point.
Iteration No: 32 ended. Search finished for the next optimal point.
Time taken: 0.0856
Function value obtained: 0.8502
Current minimum: 0.8089
Iteration No: 33 started. Searching for the next optimal point.
Iteration No: 33 ended. Search finished for the next optimal point.
Time taken: 0.1136
Function value obtained: 0.8513
Current minimum: 0.8089
Iteration No: 34 started. Searching for the next optimal point.
Iteration No: 34 ended. Search finished for the next optimal point.
Time taken: 0.1177
Function value obtained: 0.8521
Current minimum: 0.8089
Iteration No: 35 started. Searching for the next optimal point.
Iteration No: 35 ended. Search finished for the next optimal point.
Time taken: 0.1846
Function value obtained: 0.8524
Current minimum: 0.8089
Iteration No: 36 started. Searching for the next optimal point.
Iteration No: 36 ended. Search finished for the next optimal point.
Time taken: 0.1168
Function value obtained: 0.8522
Current minimum: 0.8089
Iteration No: 37 started. Searching for the next optimal point.
Iteration No: 37 ended. Search finished for the next optimal point.
Time taken: 0.3135
Function value obtained: 0.8509
Current minimum: 0.8089
Iteration No: 38 started. Searching for the next optimal point.
Iteration No: 38 ended. Search finished for the next optimal point.
Time taken: 0.1407
Function value obtained: 0.8480
Current minimum: 0.8089
Iteration No: 39 started. Searching for the next optimal point.
Iteration No: 39 ended. Search finished for the next optimal point.
Time taken: 0.1265
Function value obtained: 0.8422
Current minimum: 0.8089
Iteration No: 40 started. Searching for the next optimal point.
Iteration No: 40 ended. Search finished for the next optimal point.
Time taken: 0.1829
Function value obtained: 0.8308
Current minimum: 0.8089
Iteration No: 1 started. Evaluating function at random point.
Iteration No: 1 ended. Evaluation done at random point.
Time taken: 0.0000
Function value obtained: 56.1870
Current minimum: 56.1870
Iteration No: 2 started. Evaluating function at random point.
Iteration No: 2 ended. Evaluation done at random point.
Time taken: 0.0000
Function value obtained: 38.9618
Current minimum: 38.9618
Iteration No: 3 started. Evaluating function at random point.
Iteration No: 3 ended. Evaluation done at random point.
Time taken: 0.0000
Function value obtained: 26.2532
Current minimum: 26.2532
Iteration No: 4 started. Evaluating function at random point.
Iteration No: 4 ended. Evaluation done at random point.
Time taken: 0.0000
Function value obtained: 16.9339
Current minimum: 16.9339
Iteration No: 5 started. Evaluating function at random point.
Iteration No: 5 ended. Evaluation done at random point.
Time taken: 0.0000
Function value obtained: 28.6005
Current minimum: 16.9339
Iteration No: 6 started. Evaluating function at random point.
Iteration No: 6 ended. Evaluation done at random point.
Time taken: 0.0000
Function value obtained: 2.8191
Current minimum: 2.8191
Iteration No: 7 started. Evaluating function at random point.
Iteration No: 7 ended. Evaluation done at random point.
Time taken: 0.0000
Function value obtained: 84.3092
Current minimum: 2.8191
Iteration No: 8 started. Evaluating function at random point.
Iteration No: 8 ended. Evaluation done at random point.
Time taken: 0.0000
Function value obtained: 55.5596
Current minimum: 2.8191
Iteration No: 9 started. Evaluating function at random point.
Iteration No: 9 ended. Evaluation done at random point.
Time taken: 0.0000
Function value obtained: 30.9519
Current minimum: 2.8191
Iteration No: 10 started. Evaluating function at random point.
Iteration No: 10 ended. Evaluation done at random point.
Time taken: 0.0959
Function value obtained: 23.2016
Current minimum: 2.8191
Iteration No: 11 started. Searching for the next optimal point.
Iteration No: 11 ended. Search finished for the next optimal point.
Time taken: 0.1025
Function value obtained: 2.9634
Current minimum: 2.8191
Iteration No: 12 started. Searching for the next optimal point.
Iteration No: 12 ended. Search finished for the next optimal point.
Time taken: 0.0832
Function value obtained: 2.9931
Current minimum: 2.8191
Iteration No: 13 started. Searching for the next optimal point.
Iteration No: 13 ended. Search finished for the next optimal point.
Time taken: 0.0700
Function value obtained: 2.9966
Current minimum: 2.8191
Iteration No: 14 started. Searching for the next optimal point.
Iteration No: 14 ended. Search finished for the next optimal point.
Time taken: 0.0614
Function value obtained: 3.0051
Current minimum: 2.8191
Iteration No: 15 started. Searching for the next optimal point.
Iteration No: 15 ended. Search finished for the next optimal point.
Time taken: 0.0668
Function value obtained: 3.0078
Current minimum: 2.8191
Iteration No: 16 started. Searching for the next optimal point.
Iteration No: 16 ended. Search finished for the next optimal point.
Time taken: 0.2532
Function value obtained: 3.0076
Current minimum: 2.8191
Iteration No: 17 started. Searching for the next optimal point.
Iteration No: 17 ended. Search finished for the next optimal point.
Time taken: 0.1139
Function value obtained: 3.0060
Current minimum: 2.8191
Iteration No: 18 started. Searching for the next optimal point.
Iteration No: 18 ended. Search finished for the next optimal point.
Time taken: 0.0666
Function value obtained: 3.0036
Current minimum: 2.8191
Iteration No: 19 started. Searching for the next optimal point.
Iteration No: 19 ended. Search finished for the next optimal point.
Time taken: 0.0807
Function value obtained: 3.0007
Current minimum: 2.8191
Iteration No: 20 started. Searching for the next optimal point.
Iteration No: 20 ended. Search finished for the next optimal point.
Time taken: 0.0676
Function value obtained: 2.9976
Current minimum: 2.8191
Iteration No: 21 started. Searching for the next optimal point.
Iteration No: 21 ended. Search finished for the next optimal point.
Time taken: 0.1018
Function value obtained: 2.9944
Current minimum: 2.8191
Iteration No: 22 started. Searching for the next optimal point.
Iteration No: 22 ended. Search finished for the next optimal point.
Time taken: 0.1142
Function value obtained: 2.9910
Current minimum: 2.8191
Iteration No: 23 started. Searching for the next optimal point.
Iteration No: 23 ended. Search finished for the next optimal point.
Time taken: 0.0994
Function value obtained: 2.9876
Current minimum: 2.8191
Iteration No: 24 started. Searching for the next optimal point.
Iteration No: 24 ended. Search finished for the next optimal point.
Time taken: 0.1179
Function value obtained: 2.9840
Current minimum: 2.8191
Iteration No: 25 started. Searching for the next optimal point.
Iteration No: 25 ended. Search finished for the next optimal point.
Time taken: 0.1164
Function value obtained: 2.9802
Current minimum: 2.8191
Iteration No: 26 started. Searching for the next optimal point.
Iteration No: 26 ended. Search finished for the next optimal point.
Time taken: 0.0829
Function value obtained: 2.9761
Current minimum: 2.8191
Iteration No: 27 started. Searching for the next optimal point.
Iteration No: 27 ended. Search finished for the next optimal point.
Time taken: 0.2352
Function value obtained: 2.9714
Current minimum: 2.8191
Iteration No: 28 started. Searching for the next optimal point.
Iteration No: 28 ended. Search finished for the next optimal point.
Time taken: 0.1149
Function value obtained: 2.9659
Current minimum: 2.8191
Iteration No: 29 started. Searching for the next optimal point.
Iteration No: 29 ended. Search finished for the next optimal point.
Time taken: 0.1307
Function value obtained: 2.9588
Current minimum: 2.8191
Iteration No: 30 started. Searching for the next optimal point.
Iteration No: 30 ended. Search finished for the next optimal point.
Time taken: 0.1312
Function value obtained: 2.9489
Current minimum: 2.8191
Iteration No: 31 started. Searching for the next optimal point.
Iteration No: 31 ended. Search finished for the next optimal point.
Time taken: 0.1486
Function value obtained: 2.9336
Current minimum: 2.8191
Iteration No: 32 started. Searching for the next optimal point.
Iteration No: 32 ended. Search finished for the next optimal point.
Time taken: 0.0833
Function value obtained: 2.9066
Current minimum: 2.8191
Iteration No: 33 started. Searching for the next optimal point.
Iteration No: 33 ended. Search finished for the next optimal point.
Time taken: 0.1659
Function value obtained: 2.8551
Current minimum: 2.8191
Iteration No: 34 started. Searching for the next optimal point.
Iteration No: 34 ended. Search finished for the next optimal point.
Time taken: 0.2563
Function value obtained: 2.7712
Current minimum: 2.7712
Iteration No: 35 started. Searching for the next optimal point.
Iteration No: 35 ended. Search finished for the next optimal point.
Time taken: 0.3969
Function value obtained: 2.6908
Current minimum: 2.6908
Iteration No: 36 started. Searching for the next optimal point.
Iteration No: 36 ended. Search finished for the next optimal point.
Time taken: 0.3324
Function value obtained: 2.6555
Current minimum: 2.6555
Iteration No: 37 started. Searching for the next optimal point.
Iteration No: 37 ended. Search finished for the next optimal point.
Time taken: 0.1648
Function value obtained: 2.6471
Current minimum: 2.6471
Iteration No: 38 started. Searching for the next optimal point.
Iteration No: 38 ended. Search finished for the next optimal point.
Time taken: 0.3354
Function value obtained: 2.6433
Current minimum: 2.6433
Iteration No: 39 started. Searching for the next optimal point.
Iteration No: 39 ended. Search finished for the next optimal point.
Time taken: 0.4167
Function value obtained: 2.6402
Current minimum: 2.6402
Iteration No: 40 started. Searching for the next optimal point.
Iteration No: 40 ended. Search finished for the next optimal point.
Time taken: 0.2663
Function value obtained: 2.6374
Current minimum: 2.6374
Iteration No: 1 started. Evaluating function at random point.
Iteration No: 1 ended. Evaluation done at random point.
Time taken: 0.0013
Function value obtained: 12.8458
Current minimum: 12.8458
Iteration No: 2 started. Evaluating function at random point.
Iteration No: 2 ended. Evaluation done at random point.
Time taken: 0.0060
Function value obtained: 26.0031
Current minimum: 12.8458
Iteration No: 3 started. Evaluating function at random point.
Iteration No: 3 ended. Evaluation done at random point.
Time taken: 0.0043
Function value obtained: 24.1160
Current minimum: 12.8458
Iteration No: 4 started. Evaluating function at random point.
Iteration No: 4 ended. Evaluation done at random point.
Time taken: 0.0020
Function value obtained: 53.3861
Current minimum: 12.8458
Iteration No: 5 started. Evaluating function at random point.
Iteration No: 5 ended. Evaluation done at random point.
Time taken: 0.0010
Function value obtained: 33.7237
Current minimum: 12.8458
Iteration No: 6 started. Evaluating function at random point.
Iteration No: 6 ended. Evaluation done at random point.
Time taken: 0.0000
Function value obtained: 32.1864
Current minimum: 12.8458
Iteration No: 7 started. Evaluating function at random point.
Iteration No: 7 ended. Evaluation done at random point.
Time taken: 0.0000
Function value obtained: 11.3772
Current minimum: 11.3772
Iteration No: 8 started. Evaluating function at random point.
Iteration No: 8 ended. Evaluation done at random point.
Time taken: 0.0010
Function value obtained: 45.5451
Current minimum: 11.3772
Iteration No: 9 started. Evaluating function at random point.
Iteration No: 9 ended. Evaluation done at random point.
Time taken: 0.0000
Function value obtained: 23.8202
Current minimum: 11.3772
Iteration No: 10 started. Evaluating function at random point.
Iteration No: 10 ended. Evaluation done at random point.
Time taken: 0.0985
Function value obtained: 22.8116
Current minimum: 11.3772
Iteration No: 11 started. Searching for the next optimal point.
Iteration No: 11 ended. Search finished for the next optimal point.
Time taken: 0.1355
Function value obtained: 8.7073
Current minimum: 8.7073
Iteration No: 12 started. Searching for the next optimal point.
Iteration No: 12 ended. Search finished for the next optimal point.
Time taken: 0.0733
Function value obtained: 4.3044
Current minimum: 4.3044
Iteration No: 13 started. Searching for the next optimal point.
Iteration No: 13 ended. Search finished for the next optimal point.
Time taken: 0.1053
Function value obtained: 8.7115
Current minimum: 4.3044
Iteration No: 14 started. Searching for the next optimal point.
Iteration No: 14 ended. Search finished for the next optimal point.
Time taken: 0.0823
Function value obtained: 4.9438
Current minimum: 4.3044
Iteration No: 15 started. Searching for the next optimal point.
Iteration No: 15 ended. Search finished for the next optimal point.
Time taken: 0.0964
Function value obtained: 6.3257
Current minimum: 4.3044
Iteration No: 16 started. Searching for the next optimal point.
Iteration No: 16 ended. Search finished for the next optimal point.
Time taken: 0.2034
Function value obtained: 2.7897
Current minimum: 2.7897
Iteration No: 17 started. Searching for the next optimal point.
Iteration No: 17 ended. Search finished for the next optimal point.
Time taken: 0.0576
Function value obtained: 2.1897
Current minimum: 2.1897
Iteration No: 18 started. Searching for the next optimal point.
Iteration No: 18 ended. Search finished for the next optimal point.
Time taken: 0.0771
Function value obtained: 2.2473
Current minimum: 2.1897

In [35]:
new_samples_kpi_matern

,salt,salt_concentration,water_to_cement_ratio,antisettling_concentration,kernel,acquisition,obj_func
0,MgCl2,0.312,1.027,0.458,Matern,EI,KPI
1,CaCl2,0.416,1.387,0.000,Matern,PI,KPI
2,MgCl2,0.366,1.500,0.378,Matern,LCB_low,KPI
3,MgCl2,0.100,1.500,0.678,Matern,LCB_med,KPI
4,MgCl2,0.511,1.425,0.433,Matern,LCB_high,KPI

In [36]:
# RBF kernel
new_samples_kpi_rbf = suggest_new_samples(
    gp_kpi_rbf, obj_func="KPI", verbose=True, mute_warnings=True
)  # noqa

Warnings are muted!
Iteration No: 1 started. Evaluating function at random point.
Iteration No: 1 ended. Evaluation done at random point.
Time taken: 0.0000
Function value obtained: 32.0777
Current minimum: 32.0777
Iteration No: 2 started. Evaluating function at random point.
Iteration No: 2 ended. Evaluation done at random point.
Time taken: 0.0000
Function value obtained: 32.0777
Current minimum: 32.0777
Iteration No: 3 started. Evaluating function at random point.
Iteration No: 3 ended. Evaluation done at random point.
Time taken: 0.0000
Function value obtained: 32.0777
Current minimum: 32.0777
Iteration No: 4 started. Evaluating function at random point.
Iteration No: 4 ended. Evaluation done at random point.
Time taken: 0.0000
Function value obtained: 32.0777
Current minimum: 32.0777
Iteration No: 5 started. Evaluating function at random point.
Iteration No: 5 ended. Evaluation done at random point.
Time taken: 0.0000
Function value obtained: 32.0776
Current minimum: 32.0776
Iteration No: 6 started. Evaluating function at random point.
Iteration No: 6 ended. Evaluation done at random point.
Time taken: 0.0000
Function value obtained: 32.0777
Current minimum: 32.0776
Iteration No: 7 started. Evaluating function at random point.
Iteration No: 7 ended. Evaluation done at random point.
Time taken: 0.0000
Function value obtained: 32.0777
Current minimum: 32.0776
Iteration No: 8 started. Evaluating function at random point.
Iteration No: 8 ended. Evaluation done at random point.
Time taken: 0.0000
Function value obtained: 32.0777
Current minimum: 32.0776
Iteration No: 9 started. Evaluating function at random point.
Iteration No: 9 ended. Evaluation done at random point.
Time taken: 0.0000
Function value obtained: 32.0777
Current minimum: 32.0776
Iteration No: 10 started. Evaluating function at random point.
Iteration No: 10 ended. Evaluation done at random point.
Time taken: 0.0476
Function value obtained: 32.0777
Current minimum: 32.0776
Iteration No: 11 started. Searching for the next optimal point.
Iteration No: 11 ended. Search finished for the next optimal point.
Time taken: 0.0476
Function value obtained: 32.0777
Current minimum: 32.0776
Iteration No: 12 started. Searching for the next optimal point.
Iteration No: 12 ended. Search finished for the next optimal point.
Time taken: 0.0448
Function value obtained: 32.0777
Current minimum: 32.0776
Iteration No: 13 started. Searching for the next optimal point.
Iteration No: 13 ended. Search finished for the next optimal point.
Time taken: 0.0574
Function value obtained: 32.0608
Current minimum: 32.0608
Iteration No: 14 started. Searching for the next optimal point.
Iteration No: 14 ended. Search finished for the next optimal point.
Time taken: 0.0895
Function value obtained: 31.9042
Current minimum: 31.9042
Iteration No: 15 started. Searching for the next optimal point.
Iteration No: 15 ended. Search finished for the next optimal point.
Time taken: 0.2157
Function value obtained: 31.9648
Current minimum: 31.9042
Iteration No: 16 started. Searching for the next optimal point.
Iteration No: 16 ended. Search finished for the next optimal point.
Time taken: 0.0797
Function value obtained: 32.0250
Current minimum: 31.9042
Iteration No: 17 started. Searching for the next optimal point.
Iteration No: 17 ended. Search finished for the next optimal point.
Time taken: 0.0476
Function value obtained: 32.0556
Current minimum: 31.9042
Iteration No: 18 started. Searching for the next optimal point.
Iteration No: 18 ended. Search finished for the next optimal point.
Time taken: 0.0633
Function value obtained: 31.9948
Current minimum: 31.9042
Iteration No: 19 started. Searching for the next optimal point.
Iteration No: 19 ended. Search finished for the next optimal point.
Time taken: 0.1586
Function value obtained: 31.7960
Current minimum: 31.7960
Iteration No: 20 started. Searching for the next optimal point.
Iteration No: 20 ended. Search finished for the next optimal point.
Time taken: 0.0754
Function value obtained: 31.5048
Current minimum: 31.5048
Iteration No: 21 started. Searching for the next optimal point.
Iteration No: 21 ended. Search finished for the next optimal point.
Time taken: 0.1474
Function value obtained: 31.3656
Current minimum: 31.3656
Iteration No: 22 started. Searching for the next optimal point.
Iteration No: 22 ended. Search finished for the next optimal point.
Time taken: 0.0947
Function value obtained: 31.1041
Current minimum: 31.1041
Iteration No: 23 started. Searching for the next optimal point.
Iteration No: 23 ended. Search finished for the next optimal point.
Time taken: 0.1142
Function value obtained: 30.7841
Current minimum: 30.7841
Iteration No: 24 started. Searching for the next optimal point.
Iteration No: 24 ended. Search finished for the next optimal point.
Time taken: 0.1507
Function value obtained: 30.3835
Current minimum: 30.3835
Iteration No: 25 started. Searching for the next optimal point.
Iteration No: 25 ended. Search finished for the next optimal point.
Time taken: 0.2075
Function value obtained: 30.4326
Current minimum: 30.3835
Iteration No: 26 started. Searching for the next optimal point.
Iteration No: 26 ended. Search finished for the next optimal point.
Time taken: 0.2905
Function value obtained: 29.7058
Current minimum: 29.7058
Iteration No: 27 started. Searching for the next optimal point.
Iteration No: 27 ended. Search finished for the next optimal point.
Time taken: 0.0778
Function value obtained: 29.0130
Current minimum: 29.0130
Iteration No: 28 started. Searching for the next optimal point.
Iteration No: 28 ended. Search finished for the next optimal point.
Time taken: 0.0731
Function value obtained: 28.6292
Current minimum: 28.6292
Iteration No: 29 started. Searching for the next optimal point.
Iteration No: 29 ended. Search finished for the next optimal point.
Time taken: 0.0864
Function value obtained: 31.3265
Current minimum: 28.6292
Iteration No: 30 started. Searching for the next optimal point.
Iteration No: 30 ended. Search finished for the next optimal point.
Time taken: 0.1160
Function value obtained: 28.5906
Current minimum: 28.5906
Iteration No: 31 started. Searching for the next optimal point.
Iteration No: 31 ended. Search finished for the next optimal point.
Time taken: 0.0848
Function value obtained: 27.9745
Current minimum: 27.9745
Iteration No: 32 started. Searching for the next optimal point.
Iteration No: 32 ended. Search finished for the next optimal point.
Time taken: 0.1327
Function value obtained: 28.5936
Current minimum: 27.9745
Iteration No: 33 started. Searching for the next optimal point.
Iteration No: 33 ended. Search finished for the next optimal point.
Time taken: 0.1270
Function value obtained: 26.5240
Current minimum: 26.5240
Iteration No: 34 started. Searching for the next optimal point.
Iteration No: 34 ended. Search finished for the next optimal point.
Time taken: 0.1462
Function value obtained: 24.9265
Current minimum: 24.9265
Iteration No: 35 started. Searching for the next optimal point.
Iteration No: 35 ended. Search finished for the next optimal point.
Time taken: 0.3550
Function value obtained: 22.5070
Current minimum: 22.5070
Iteration No: 36 started. Searching for the next optimal point.
Iteration No: 36 ended. Search finished for the next optimal point.
Time taken: 0.1671
Function value obtained: 19.6775
Current minimum: 19.6775
Iteration No: 37 started. Searching for the next optimal point.
Iteration No: 37 ended. Search finished for the next optimal point.
Time taken: 0.1274
Function value obtained: 16.9737
Current minimum: 16.9737
Iteration No: 38 started. Searching for the next optimal point.
Iteration No: 38 ended. Search finished for the next optimal point.
Time taken: 0.1426
Function value obtained: 15.6446
Current minimum: 15.6446
Iteration No: 39 started. Searching for the next optimal point.
Iteration No: 39 ended. Search finished for the next optimal point.
Time taken: 0.1103
Function value obtained: 16.0187
Current minimum: 15.6446
Iteration No: 40 started. Searching for the next optimal point.
Iteration No: 40 ended. Search finished for the next optimal point.
Time taken: 0.1431
Function value obtained: 16.7335
Current minimum: 15.6446
Iteration No: 1 started. Evaluating function at random point.
Iteration No: 1 ended. Evaluation done at random point.
Time taken: 0.0158
Function value obtained: 32.0777
Current minimum: 32.0777
Iteration No: 2 started. Evaluating function at random point.
Iteration No: 2 ended. Evaluation done at random point.
Time taken: 0.0000
Function value obtained: 32.0777
Current minimum: 32.0777
Iteration No: 3 started. Evaluating function at random point.
Iteration No: 3 ended. Evaluation done at random point.
Time taken: 0.0000
Function value obtained: 32.0777
Current minimum: 32.0777
Iteration No: 4 started. Evaluating function at random point.
Iteration No: 4 ended. Evaluation done at random point.
Time taken: 0.0000
Function value obtained: 32.0777
Current minimum: 32.0777
Iteration No: 5 started. Evaluating function at random point.
Iteration No: 5 ended. Evaluation done at random point.
Time taken: 0.0000
Function value obtained: 32.0777
Current minimum: 32.0777
Iteration No: 6 started. Evaluating function at random point.
Iteration No: 6 ended. Evaluation done at random point.
Time taken: 0.0000
Function value obtained: 32.0777
Current minimum: 32.0777
Iteration No: 7 started. Evaluating function at random point.
Iteration No: 7 ended. Evaluation done at random point.
Time taken: 0.0000
Function value obtained: 32.0777
Current minimum: 32.0777
Iteration No: 8 started. Evaluating function at random point.
Iteration No: 8 ended. Evaluation done at random point.
Time taken: 0.0000
Function value obtained: 32.0777
Current minimum: 32.0777
Iteration No: 9 started. Evaluating function at random point.
Iteration No: 9 ended. Evaluation done at random point.
Time taken: 0.0000
Function value obtained: 32.0777
Current minimum: 32.0777
Iteration No: 10 started. Evaluating function at random point.
Iteration No: 10 ended. Evaluation done at random point.
Time taken: 0.1795
Function value obtained: 32.0777
Current minimum: 32.0777
Iteration No: 11 started. Searching for the next optimal point.
Iteration No: 11 ended. Search finished for the next optimal point.
Time taken: 0.0688
Function value obtained: 31.9843
Current minimum: 31.9843
Iteration No: 12 started. Searching for the next optimal point.
Iteration No: 12 ended. Search finished for the next optimal point.
Time taken: 0.0495
Function value obtained: 32.0777
Current minimum: 31.9843
Iteration No: 13 started. Searching for the next optimal point.
Iteration No: 13 ended. Search finished for the next optimal point.
Time taken: 0.0479
Function value obtained: 32.0777
Current minimum: 31.9843
Iteration No: 14 started. Searching for the next optimal point.
Iteration No: 14 ended. Search finished for the next optimal point.
Time taken: 0.0832
Function value obtained: 32.0777
Current minimum: 31.9843
Iteration No: 15 started. Searching for the next optimal point.
Iteration No: 15 ended. Search finished for the next optimal point.
Time taken: 0.1677
Function value obtained: 32.1415
Current minimum: 31.9843
Iteration No: 16 started. Searching for the next optimal point.
Iteration No: 16 ended. Search finished for the next optimal point.
Time taken: 0.0983
Function value obtained: 32.0777
Current minimum: 31.9843
Iteration No: 17 started. Searching for the next optimal point.
Iteration No: 17 ended. Search finished for the next optimal point.
Time taken: 0.0873
Function value obtained: 32.0777
Current minimum: 31.9843
Iteration No: 18 started. Searching for the next optimal point.
Iteration No: 18 ended. Search finished for the next optimal point.
Time taken: 0.1136
Function value obtained: 31.9821
Current minimum: 31.9821
Iteration No: 19 started. Searching for the next optimal point.
Iteration No: 19 ended. Search finished for the next optimal point.
Time taken: 0.0485
Function value obtained: 31.5133
Current minimum: 31.5133
Iteration No: 20 started. Searching for the next optimal point.
Iteration No: 20 ended. Search finished for the next optimal point.
Time taken: 0.0697
Function value obtained: 31.9872
Current minimum: 31.5133
Iteration No: 21 started. Searching for the next optimal point.
Iteration No: 21 ended. Search finished for the next optimal point.
Time taken: 0.1293
Function value obtained: 32.0777
Current minimum: 31.5133
Iteration No: 22 started. Searching for the next optimal point.
Iteration No: 22 ended. Search finished for the next optimal point.
Time taken: 0.1074
Function value obtained: 32.0777
Current minimum: 31.5133
Iteration No: 23 started. Searching for the next optimal point.
Iteration No: 23 ended. Search finished for the next optimal point.
Time taken: 0.0757
Function value obtained: 32.0664
Current minimum: 31.5133
Iteration No: 24 started. Searching for the next optimal point.
Iteration No: 24 ended. Search finished for the next optimal point.
Time taken: 0.0687
Function value obtained: 32.0777
Current minimum: 31.5133
Iteration No: 25 started. Searching for the next optimal point.
Iteration No: 25 ended. Search finished for the next optimal point.
Time taken: 0.1649
Function value obtained: 32.0777
Current minimum: 31.5133
Iteration No: 26 started. Searching for the next optimal point.
Iteration No: 26 ended. Search finished for the next optimal point.
Time taken: 0.0844
Function value obtained: 31.5389
Current minimum: 31.5133
Iteration No: 27 started. Searching for the next optimal point.
Iteration No: 27 ended. Search finished for the next optimal point.
Time taken: 0.0992
Function value obtained: 31.3182
Current minimum: 31.3182
Iteration No: 28 started. Searching for the next optimal point.
Iteration No: 28 ended. Search finished for the next optimal point.
Time taken: 0.1162
Function value obtained: 31.2686
Current minimum: 31.2686
Iteration No: 29 started. Searching for the next optimal point.
Iteration No: 29 ended. Search finished for the next optimal point.
Time taken: 0.1001
Function value obtained: 31.0630
Current minimum: 31.0630
Iteration No: 30 started. Searching for the next optimal point.
Iteration No: 30 ended. Search finished for the next optimal point.
Time taken: 0.0829
Function value obtained: 30.8737
Current minimum: 30.8737
Iteration No: 31 started. Searching for the next optimal point.
Iteration No: 31 ended. Search finished for the next optimal point.
Time taken: 0.1003
Function value obtained: 30.5606
Current minimum: 30.5606
Iteration No: 32 started. Searching for the next optimal point.
Iteration No: 32 ended. Search finished for the next optimal point.
Time taken: 0.0656
Function value obtained: 30.2518
Current minimum: 30.2518
Iteration No: 33 started. Searching for the next optimal point.
Iteration No: 33 ended. Search finished for the next optimal point.
Time taken: 0.0836
Function value obtained: 29.8440
Current minimum: 29.8440
Iteration No: 34 started. Searching for the next optimal point.
Iteration No: 34 ended. Search finished for the next optimal point.
Time taken: 0.0822
Function value obtained: 29.3594
Current minimum: 29.3594
Iteration No: 35 started. Searching for the next optimal point.
Iteration No: 35 ended. Search finished for the next optimal point.
Time taken: 0.1352
Function value obtained: 28.7163
Current minimum: 28.7163
Iteration No: 36 started. Searching for the next optimal point.
Iteration No: 36 ended. Search finished for the next optimal point.
Time taken: 0.3315
Function value obtained: 27.7072
Current minimum: 27.7072
Iteration No: 37 started. Searching for the next optimal point.
Iteration No: 37 ended. Search finished for the next optimal point.
Time taken: 0.1304
Function value obtained: 26.2172
Current minimum: 26.2172
Iteration No: 38 started. Searching for the next optimal point.
Iteration No: 38 ended. Search finished for the next optimal point.
Time taken: 0.2835
Function value obtained: 25.1101
Current minimum: 25.1101
Iteration No: 39 started. Searching for the next optimal point.
Iteration No: 39 ended. Search finished for the next optimal point.
Time taken: 0.1843
Function value obtained: 22.6409
Current minimum: 22.6409
Iteration No: 40 started. Searching for the next optimal point.
Iteration No: 40 ended. Search finished for the next optimal point.
Time taken: 0.1506
Function value obtained: 20.4558
Current minimum: 20.4558
Iteration No: 1 started. Evaluating function at random point.
Iteration No: 1 ended. Evaluation done at random point.
Time taken: 0.0010
Function value obtained: 32.0777
Current minimum: 32.0777
Iteration No: 2 started. Evaluating function at random point.
Iteration No: 2 ended. Evaluation done at random point.
Time taken: 0.0010
Function value obtained: 32.0777
Current minimum: 32.0777
Iteration No: 3 started. Evaluating function at random point.
Iteration No: 3 ended. Evaluation done at random point.
Time taken: 0.0010
Function value obtained: 32.0570
Current minimum: 32.0570
Iteration No: 4 started. Evaluating function at random point.
Iteration No: 4 ended. Evaluation done at random point.
Time taken: 0.0000
Function value obtained: 32.0777
Current minimum: 32.0570
Iteration No: 5 started. Evaluating function at random point.
Iteration No: 5 ended. Evaluation done at random point.
Time taken: 0.0010
Function value obtained: 32.0777
Current minimum: 32.0570
Iteration No: 6 started. Evaluating function at random point.
Iteration No: 6 ended. Evaluation done at random point.
Time taken: 0.0010
Function value obtained: 31.8611
Current minimum: 31.8611
Iteration No: 7 started. Evaluating function at random point.
Iteration No: 7 ended. Evaluation done at random point.
Time taken: 0.0000
Function value obtained: 32.0777
Current minimum: 31.8611
Iteration No: 8 started. Evaluating function at random point.
Iteration No: 8 ended. Evaluation done at random point.
Time taken: 0.0010
Function value obtained: 32.0777
Current minimum: 31.8611
Iteration No: 9 started. Evaluating function at random point.
Iteration No: 9 ended. Evaluation done at random point.
Time taken: 0.0000
Function value obtained: 32.0844
Current minimum: 31.8611
Iteration No: 10 started. Evaluating function at random point.
Iteration No: 10 ended. Evaluation done at random point.
Time taken: 0.0504
Function value obtained: 32.0777
Current minimum: 31.8611
Iteration No: 11 started. Searching for the next optimal point.
Iteration No: 11 ended. Search finished for the next optimal point.
Time taken: 0.0316
Function value obtained: 32.0777
Current minimum: 31.8611
Iteration No: 12 started. Searching for the next optimal point.
Iteration No: 12 ended. Search finished for the next optimal point.
Time taken: 0.0527
Function value obtained: 32.0777
Current minimum: 31.8611
Iteration No: 13 started. Searching for the next optimal point.
Iteration No: 13 ended. Search finished for the next optimal point.
Time taken: 0.0477
Function value obtained: 31.8905
Current minimum: 31.8611
Iteration No: 14 started. Searching for the next optimal point.
Iteration No: 14 ended. Search finished for the next optimal point.
Time taken: 0.0641
Function value obtained: 32.0777
Current minimum: 31.8611
Iteration No: 15 started. Searching for the next optimal point.
Iteration No: 15 ended. Search finished for the next optimal point.
Time taken: 0.0886
Function value obtained: 32.0777
Current minimum: 31.8611
Iteration No: 16 started. Searching for the next optimal point.
Iteration No: 16 ended. Search finished for the next optimal point.
Time taken: 0.2021
Function value obtained: 32.0777
Current minimum: 31.8611
Iteration No: 17 started. Searching for the next optimal point.
Iteration No: 17 ended. Search finished for the next optimal point.
Time taken: 0.0949
Function value obtained: 32.0777
Current minimum: 31.8611
Iteration No: 18 started. Searching for the next optimal point.

In [37]:
new_samples_kpi_rbf

,salt,salt_concentration,water_to_cement_ratio,antisettling_concentration,kernel,acquisition,obj_func
0,Mg(NO3)2,0.237,1.286,1.719,RBF,EI,KPI
1,Mg(NO3)2,0.485,1.077,0.027,RBF,PI,KPI
2,KAl(SO4)2,0.854,1.394,0.590,RBF,LCB_low,KPI
3,MgSO4,0.557,0.937,0.085,RBF,LCB_med,KPI
4,MgSO4,0.706,1.452,0.254,RBF,LCB_high,KPI

## Saving the new suggestions in the original excel sheet

In [38]:
# Combine sets of new samples
new_samples = pd.concat(
    [
        new_samples_energy_matern,
        new_samples_energy_rbf,
        new_samples_kpi_matern,
        new_samples_kpi_rbf,
    ],
    ignore_index=True,
)

new_samples.insert(0, "opt_round", opt_round + 1)  # add optimization round

# Read the existing Excel sheet into a DataFrame
experiment_data = pd.read_excel(data_dir / data_file, sheet_name="Datasheet")
# Append the new data to the existing DataFrame
combined_data = pd.concat(
    [experiment_data, new_samples], ignore_index=True, axis=0
)  # noqa

# Write the updated DataFrame back to the same Excel sheet
with pd.ExcelWriter(
    data_dir / data_file, engine="openpyxl", mode="a", if_sheet_exists="replace"  # noqa
) as writer:
    combined_data.to_excel(writer, sheet_name="Datasheet", index=False)

print(
    "New batch of 20 samples suggested. Please conduct experiments and update the dataset."  # noqa
)

New batch of 20 samples suggested. Please conduct experiments and update the dataset.